font:
  face: DejaVuSans.ttf
  size: 14
screen:
  brightness: 30
  rotation: 0
  timeout: 60
icon:
  mdi:
    css: materialdesignicons.css
    face: materialdesignicons-webfont.ttf
  image:
    on: On.png
    off: Off.png
    blank: Blank.png
  color:
    on: "#FFFFFF"
    off: "#777777"
homeassistant:
  url: https://your.hass.install.here/
  token: your_long_lived_token_here
  entities: